### ISSUE TITLE
<GroupedColumn> not exist in v0.3.0

### ISSUE THREAD

**Issue by xccu** [ant-design-blazor/ant-design-charts-blazor#111]
<GroupedColumn> and GroupedColumnConfig  not exist  in v0.3.0 dll package and source code:
https://github.com/ant-design-blazor/ant-design-charts-blazor

**Comment by MaggiGorengAyam** [comment]
Hi @xccu , as per the [upgrade guide](https://g2plot.antv.antgroup.com/en/manual/upgrade) , you should use a `Column`, with the `IsGroup = true` in the config. Here is the [demo code](https://github.com/ant-design-blazor/ant-design-charts-blazor/blob/master/src/AntDesign.Charts.Docs/Demos/Column/Grouped_Column_Chart.razor).

**Comment by xccu** [comment]
Hi @MaggiGorengAyam  when I use the demo code, the chart looks like this:
![issue](https://user-images.githubusercontent.com/7534189/212871933-d5ea65ed-0e91-4f87-82f9-21dc74c2333b.png)
the demo in https://antblazor.com/en-US/charts/column shown like this:
![demo](https://user-images.githubusercontent.com/7534189/212872214-54f90c0b-c569-4f3d-b644-df8377a4d39d.png)

**Comment by MaggiGorengAyam** [comment]
@xccu The current live demo is not up to date, as the main contributor is working on a new refined documentation. So the data and config there is outdated. Please try with this [demo code](https://github.com/ant-design-blazor/ant-design-charts-blazor/blob/master/src/AntDesign.Charts.Docs/Demos/Column/Grouped_Column_Chart.razor) by copying the config and the data. You should be able to see the chart generated as per below. 
![image](https://user-images.githubusercontent.com/31787139/212876708-c1eb0bcf-0819-4bab-aae8-b49dfbd43f46.png)
Alternatively, you can run the `Docs.Server` project and navigate to `/Grouped_Column_Chart`.

**Comment by xccu** [comment]
@MaggiGorengAyam Hi,I've solved the problem by modified 
<script src="https://unpkg.com/@antv/g2plot@1.1.28/dist/g2plot.js"></script>
to:
<script src="https://unpkg.com/@@antv/g2plot@latest/dist/g2plot.min.js"></script> 
thanks a lot  :)
