### ISSUE TITLE
Slider on Line chart did't work

### ISSUE THREAD

**Issue by jusonleung** [ant-design-blazor/ant-design-charts-blazor#113]
`LineConfig VoltageTimeConfig = new LineConfig
        {
            Padding = "auto",
            AutoFit = true,
            XField = "dateTimeStr",
            YField = "voltage",
            Interactions = new[]
                {
            new Interaction
            {
                Type = "slider",
                Cfg = new
                {
                    start = 0.1,
                    end = 0.2
                }
            }
        }
        };`
        
The slider in my line chart did't show up
![image](https://user-images.githubusercontent.com/32033114/222953912-be5091a5-0d19-4364-93fb-9ebf0ed42255.png)

**Comment by MaggiGorengAyam** [comment]
Hi @jusonleung , 

Instead of doing `Interactions = new[]...`, replace it with the following:
```
Slider = new Slider
{
    Start = 0.1,
    End = 0.2
}
```
Here is the complete code:
```
LineConfig VoltageTimeConfig = new LineConfig
    {
        Padding = "auto",
        AutoFit = true,
        XField = "dateTimeStr",
        YField = "voltage",
        Slider = new Slider
        {
            Start = 0.1,
            End = 0.2
        }
    };
```

**Comment by jusonleung** [comment]
Thank you for 

> Hi @jusonleung ,
> 
> Instead of doing `Interactions = new[]...`, replace it with the following:
> 
> ```
> Slider = new Slider
> {
>     Start = 0.1,
>     End = 0.2
> }
> ```
> 
> Here is the complete code:
> 
> ```
> LineConfig VoltageTimeConfig = new LineConfig
>     {
>         Padding = "auto",
>         AutoFit = true,
>         XField = "dateTimeStr",
>         YField = "voltage",
>         Slider = new Slider
>         {
>             Start = 0.1,
>             End = 0.2
>         }
>     };
> ```

Thank you for you helping.

Also, I wonder why RegressionLine on scatter chart will occur exception 

```
Config = new ScatterConfig
            {
                AutoFit = true,
                Padding = "auto",
                XField = against,
                YField = prop.Name.ToLower(),
                PointStyle = new GraphicStyle
                {
                    Stroke = "#777777",
                    LineWidth = 1,
                    Fill = "#5B8FF9",
                },
                RegressionLine = new RegressionLineConfig
                {
                    Type = "quad",
                }
            };
```

> Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
> Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Cannot return as T1 as result is T0
> 
> System.InvalidOperationException: Cannot return as T1 as result is T0
>    at OneOf.OneOf`2.get_AsT1()
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Converters.ArrayConverter`2.OnWriteResume(Utf8JsonWriter writer, TElement[] array, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
>    at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
>    at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
>    at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
>    at AntDesign.Charts.ChartComponentBase`1.Create()
>    at AntDesign.Charts.ChartComponentBase`1.OnAfterRenderAsync(Boolean firstRender)
> Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'kpC_-sC0LDs2Xny6vXs55BQ7ZdbY5avGB5QQ9KPkocc'.
> 
> System.AggregateException: One or more errors occurred. (Cannot return as T1 as result is T0)
>  ---> System.InvalidOperationException: Cannot return as T1 as result is T0
>    at OneOf.OneOf`2.get_AsT1()
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
>    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Converters.ArrayConverter`2.OnWriteResume(Utf8JsonWriter writer, TElement[] array, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
>    at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
>    at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
>    at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
>    at AntDesign.Charts.ChartComponentBase`1.Create()
>    at AntDesign.Charts.ChartComponentBase`1.OnAfterRenderAsync(Boolean firstRender)
>    --- End of inner exception stack trace ---
> Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
> 
> Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
>    at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
>    at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
>    at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
>    at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
>    at AntDesign.Tabs.ResetSizes()
>    at AntDesign.Tabs.OnAfterRenderAsync(Boolean firstRender)
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
> Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'kpC_-sC0LDs2Xny6vXs55BQ7ZdbY5avGB5QQ9KPkocc'.
> 
> Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
>    at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
>    at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
>    at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
>    at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
>    at AntDesign.Tabs.ResetSizes()
>    at AntDesign.Tabs.OnAfterRenderAsync(Boolean firstRender)
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
