### ISSUE TITLE
AntBlazor.com chart instructions are outdated

### ISSUE THREAD

**Issue by SvdSinner** [ant-design-blazor/ant-design-charts-blazor#122]
The public website: https://antblazor.com/en-US/charts/introduce has dated instructions that no longer work with current versions of ant-design-charts-blazor .  There is already an updated version in the the code that can be run locally if you pull the source code.

However, having an obsolete version of the instructions as the first thing that Google finds is a bad thing.

**Comment by dzysdy** [comment]
我用代码跑出来的文档，也是只有效果没有示例，在哪能看见怎么使用呢？

**Comment by jeffersyuan1976** [comment]
New version had been updated from 0.19.2 of antblazor

**Comment by ElderJames** [comment]
Thank you @jeffersyuan1976
