### ISSUE TITLE
Gauge Chart using ant design chart 0.3.1 is not working properly 

### ISSUE THREAD

**Issue by nanizdo** [ant-design-blazor/ant-design-charts-blazor#125]
I am trying to create a gauge chart using ant design blazor with the latest version available 0.3.1, following the documentation published on the official website, a lot of things have been changed yet there are no updates available, it would be great if you update the documentation on your website or just refer to me a working example of a gauge chart.

**Comment by superjerry88** [comment]
Here is a working example of gauge

https://github.com/ant-design-blazor/ant-design-charts-blazor/blob/master/src/AntDesign.Charts.Docs/Demos/Gauge/Gauge_Chart.razor
