### ISSUE TITLE
最新的发版0.51里没有ColumnLine ????

### ISSUE THREAD

**Issue by zitjubiz** [ant-design-blazor/ant-design-charts-blazor#139]
这个网址有 https://antblazor.com/zh-CN/charts/combo
有混合图表, 有相应的代码,  <ColumnLine Data="@(new[] {uvData, transformData})" Config="config1" />
但最新的发版0.51里没有ColumnLine ????

**Comment by jeffersyuan1976** [comment]
ColumnLine changed to Column
