### ISSUE TITLE
Missing file in unpkg for g2plot, incompatible g2plot version  

### ISSUE THREAD

**Issue by Kesade** [ant-design-blazor/ant-design-charts-blazor#23]
There is a problem after recent releases in https://unpkg.com/@antv/g2plot@latest/dist/.
The file "g2plot.js" is no longer available there and the file "g2plot.min.js" is not working. 

It is also causing problems on yours documentation website - https://ant-design-blazor.github.io/en-US/charts/bullet.

**Comment by NPadrutt** [comment]
is there a solution for this?

**Comment by Kesade** [comment]
@NPadrutt Some time ago I checked on their documentation and it was working - however I did not see any update on github. So I do not know actually - what I did so it would work I took specific version of the file from https://unpkg.com/browse/@antv/g2plot@1.1.28/dist/ here and it helped for me. Maybe the current version works well

**Comment by NPadrutt** [comment]
aah, so you just added the missing file manually?
