### ISSUE TITLE
Change Chart Width

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-charts-blazor#44]
Hi All,

I have tried to change the width of the chart via Config => Width. But that does not work!

Currently, a chart takes the whole line, which looks ugly when there are only a few values. I want to define the width of the chart myself, so that a table can be placed next to the chart (similar to what is done in MS Excel).

How do I change the width of the chart programmatically?

Thanks

**Comment by MaggiGorengAyam** [comment]
@ElderJames this issue has been resolved in PR #99 .

**Comment by ElderJames** [comment]
@MaggiGorengAyam  Thank you!
