### ISSUE TITLE
Can it be used to plot candle stick?

### ISSUE THREAD

**Issue by zenchanhk** [ant-design-blazor/ant-design-charts-blazor#51]
As titled, if yes, how？thanks a lot in advance.

**Comment by cwijk** [comment]
Same here. Great work what you're doing. Currently using the Area chart. Works like a charm. Would be even better if we have a candlestick/stock chart. Thanks a lot!

**Comment by MaggiGorengAyam** [comment]
@ElderJames I believe this issue has already been resolved in PR #77 with [demo](https://github.com/ant-design-blazor/ant-design-charts-blazor/blob/master/src/AntDesign.Charts.Docs/Demos/Column/Stock_Chart.razor).

**Comment by ElderJames** [comment]
Ok, thank you @MaggiGorengAyam
