### ISSUE TITLE
现在的BlazorChart不匹配最新的2.x的g2plot，请问作者还会更新嘛

### ISSUE THREAD

**Issue by Ashhhhhh520** [ant-design-blazor/ant-design-charts-blazor#59]
现在的BlazorChart不匹配最新的2.x的g2plot，请问作者还会更新嘛

**Comment by ElderJames** [comment]
你好，我们目前Charts这边维护比较有限，如果你有兴趣，欢迎提交PR，帮助我们维护这个项目。

Hi, we currently have more limited maintenance on the Charts side, so if you are interested, feel free to submit a PR and help us maintain the project.

**Comment by ElderJames** [comment]
0.2.2已发布，支持 g2plot 2.x 。欢迎试用。
