### ISSUE TITLE
IsStack property

### ISSUE THREAD

**Issue by quirynen** [ant-design-blazor/ant-design-charts-blazor#60]
Hi,

In the line config on g2plot, there is a possibility to stack points with same data (  isStack :true).
But I don't see this possibility here, is there a way to do that or is this not currently implemented?

**Comment by ElderJames** [comment]
Hi @quirynen , we haven't maintained this project for a long time and there may be some API's that haven't been added up. Please help us fix this if you would like.

**Comment by quirynen** [comment]
I just create a PR, let me know if it's ok

**Comment by ElderJames** [comment]
@quirynen Thank you a lot! I have merged and release soon.

**Comment by quirynen** [comment]
Perfect, If you need some help on other features, I can maybe try to find some time
