### ISSUE TITLE
GuideLine should be replaced by Annotations

### ISSUE THREAD

**Issue by bezysoftware** [ant-design-blazor/ant-design-charts-blazor#68]
In v2 of G2Plot setting `GuideLine` does nothing, the config has moved to `annotations`

E.g. https://g2plot.antv.vision/en/docs/api/plots/column#-line-annotation

**Comment by MaggiGorengAyam** [comment]
@ElderJames this issue has been resolved in PR #102 .

**Comment by ElderJames** [comment]
Thank you @MaggiGorengAyam .
