### ISSUE TITLE
Slider doesn't seem implemented

### ISSUE THREAD

**Issue by acpt** [ant-design-blazor/ant-design-charts-blazor#75]
I don't know why you put slider in Interactions, shouldn't it reside as a direct class instead of an array?
I can't make it work as it is...
Made a fork changing class's to make slider a direct parameter and works.... but was just for testing porpuse

**Comment by MaggiGorengAyam** [comment]
@ElderJames this issue has been resolved in PR #102 .

**Comment by ElderJames** [comment]
Thank you @MaggiGorengAyam !
