### ISSUE TITLE
xField,yField display text settings

### ISSUE THREAD

**Issue by SoaSoftNet** [ant-design-blazor/ant-design-charts-blazor#85]
xField = "year",
        yField = "value",
     How to set display text？
   Add xFieldText?yFieldText property？

**Comment by dkosinskyi** [comment]
XAxis = new CatAxis
            {
                Visible = true,
                Label = new BaseAxisLabel
                {
                    Visible = true,
                    AutoHide = false,
                    AutoRotate = true,
                    //Rotate = 45
                }
            },
